flags:
extra-package-dbs: []
packages:
- opentracing
- opentracing-cloudtrace
- opentracing-examples
- opentracing-http-client
- opentracing-jaeger
- opentracing-wai
- opentracing-zipkin-common
- opentracing-zipkin-v1
- opentracing-zipkin-v2
extra-deps:
- gogol-0.3.0
- gogol-cloudtrace-0.3.0
- gogol-core-0.3.0
- gogol-logging-0.3.0
- network-2.8.0.1
- thrift-0.13.0
- vinyl-0.13.0

resolver: lts-16.15
